name: 'Wayback Machine'
description: 'Action for submitting a website to the Wayback Machine'
author: 'Jamie Magee'
branding:
  icon: 'clock'
  color: 'red'
inputs:
  url:
    required: true
    description: 'URL to submit to the wayback machine'
  saveErrors:
    required: false
    default: 'true'
    description: 'If true, save HTTP errors as well'
  saveOutlinks:
    required: false
    default: 'false'
    description: 'If true, save all links to external sites'
  saveScreenshot:
    required: false
    default: 'false'
    description: 'If true, save a screenshot of the site'
outputs:
  wayback_url:
    description: 'The Wayback Machine URL'
runs:
  using: 'node20'
  main: 'dist/index.js'
